---

- name: Update apt
  apt: update_cache=yes

- name: Set timezone to American/Denver
  timezone:
    name: "{{ timezone }}"

# - name: Include samdoran.fish
#   include_role:
#      name: galaxy_roles/samdoran.fish