---
virtualHost: pihole-k8.piccola.us

DNS1: 10.0.3.24
DNS2: 10.0.3.22

serviceTCP:
  #loadBalancerIP: 10.0.3.220
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceUDP:
  #loadBalancerIP: 10.0.3.220
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-ingress
    kubernetes.io/tls-acme: "true"
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  enabled: true
  hosts:
    - pihole-k8.piccola.us
  tls:
  - hosts:
    - pihole-k8.piccola.us
    secretName: pihole-k8
#  rules:
#  - host: pihole-k8.piccola.us
#    http:
#      paths:
#      - backend:
#          serviceName: pihole-kubernetes-tcp
#          servicePort: 80
#        path: /

persistentVolumeClaim:
  enabled: true
  existingClaim: pihole
  size: 200mi
