---

- name: configure vtp
  ios_config:
    lines:
      - vtp domain piccola
      - "vtp password {{ vtp_server_password }}"
      - vtp mode server
      - vtp pruning
      - vtp version 1

- name: configure vlans
  ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: "{{ item.state }}"
        shutdown: "{{ item.shutdown }}"
    state: merged
  with_items:
     - { name: default, vlan_id: 1, state: active, shutdown: disabled }
     - { name: lan, vlan_id: 3, state: active, shutdown: disabled }
     - { name: guests, vlan_id: 8, state: active, shutdown: disabled }
     - { name: iot_devices, vlan_id: 9, state: active, shutdown: disabled }
     - { name: ip_cameras, vlan_id: 10, state: active, shutdown: disabled }
     - { name: cl_ppoe, vlan_id: 201, state: active, shutdown: disabled }

- name: configure general interfaces
  ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - "description {{ item.description }}"
      - "switchport mode {{ item.mode }}"
      - "switchport access vlan {{ item.vlan }}"
  with_items:
    - {interface: GigabitEthernet0/1, description: alley_camera, mode: access, vlan: 10}
    - {interface: GigabitEthernet0/2, description: south_yard camera, mode: access, vlan: 10}
    - {interface: GigabitEthernet0/3, description: backyard camera, mode: access, vlan: 10}
    - {interface: GigabitEthernet0/4, description: front_porch camera, mode: access, vlan: 10}
    - {interface: GigabitEthernet0/5, description: printer, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/6, description: office-a, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/7, description: office-b, mode: access, vlan: 3}

- name: configure unfi-ap-pro interface
  ios_config:
    parents: interface GigabitEthernet0/8
    lines:
      - description unfi-ap-pro
      - switchport mode trunk
      - switchport trunk allowed vlan 1,3,8-10

- name: configure century_link_ont interface
  ios_config:
    parents: interface GigabitEthernet0/9
    lines:
      - description century_link_ont
      - switchport mode trunk
      - switchport trunk allowed vlan 201

- name: configure cs-logan-0 <-> sg300-a interface
  ios_config:
    parents: interface GigabitEthernet0/24
    lines:
      - description cs-logan-0 <-> sg300-a
      - switchport mode trunk
