---

- name: Install pip3 packages
  become: true
  pip:
    name:
    - adafruit-circuitpython-bme280
    state: present
    executable: pip3

- name: Copy over python script
  become: true
  tags: python
  template:
    src: "{{ role_path }}/files/Get-BME280Stats.py"
    dest: "{{ python_script_path }}"
    owner: pi
    mode: 0755

- name: Copy over telegraf.conf
  tags: telegraf, host
  template:
    src: "{{ role_path }}/files/telegraf.conf"
    dest: "{{ telegraf_conf_path }}"
  register: telegrafconf
  when: telegraf_stats

- name: Restart telegraf
  tags: telegraf
  service:
    name: telegraf
    state: restarted
  when: telegrafconf.changed and telegraf_stats
