---

- name: Include tailscale tasks
  include_tasks: tailscale.yml
  tags: [always, ts]

- name: Install packages
  apt:
    pkg:
      - parted
      - iperf3
      - bmon
    state: latest

- name: Include telegraf tasks
  include_tasks: telegraf.yml
  tags: always
