---
ansible_ssh_private_key_file: ./keys/id_rsa
timezone: America/Denver
telegraf_output_urls: http://influxdb.piccola.us:8086
telegraf_output_database_lin: lin_metrics
telegraf_conf_path: /etc/telegraf/telegraf.conf
telegraf_agent_interval: 30s
ntp_servers:
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org
  - 2.north-america.pool.ntp.org
  - 3.north-america.pool.ntp.org
dhcp_servers:
  - 10.0.3.24
  - 10.0.3.22
name_servers:
  - 10.0.3.24
  - 10.0.3.22
personal_user: joey
domain_dns_name: piccola.us
domain_win_name: ad.piccola.us
personal_user_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8XvA+caTkxvxQiJRAc5gY7B/WziUadAVl4AMd0KYvly25/prJ8jRFbH1Dry9g3dyKBMjgBHonKXRRGGv6p2wiIf77Dg2ikL0p4+FsLJ7wI8OUEXNjR0OMq7lftf78qAyVBnzFDL0B198mwCTyq3j3NDbIGXkSg5ArEwsy2hteWp6QZy21SZ3p4MUhgHffPRTvemQjMZSE2uML6xlgkgFsXx7wPgVqZot3phrQnengzSHtD7n6fKkKWuaQASZgX2Ysc8VAvypQ9Am/oHxSdVHS/0f+wEeg3MBSXUxaizJfwXkuFtZtMiOVGyVJOojpWOeJEPZL8NqDxfXhyS07iuXTLkOed6yi1OWC+VlBwlLWUzjKF5zLeF7XawNc3TAx7x+T4yDzgZTbqnn4xcUDCVGFxq550DobryHkHLx6sFWsblhSAkdeuykZEPNeTSFLyi4MnX78gGe7vqr7ibJql7wul95twaELHaApcfcrO5qEOzd50WfLkiySgAUmFrwj/+M= Joey Piccola
