version: "3"
services:
  dynamicdns:
    image: dynamicdns
    container_name: dynamicdns
    volumes:
      - ./scripts/:/scripts
    restart: unless-stopped
    environment:
      - CRON_STRINGS=*/10 * * * * pwsh /scripts/Update-DNS.ps1 >> /var/log/cron.log 2>&1
