---

- name: configure general vlans
  edgeos_config:
    lines:
      - set interfaces ethernet {{ item.l3_interface }} vif {{ item.vlan_id }} address {{ item.l3_ip }}/{{ item.network_mask }}
      - set interfaces ethernet {{ item.l3_interface }} vif {{ item.vlan_id }} description {{ item.name }}
      - set interfaces ethernet {{ item.l3_interface }} vif {{ item.vlan_id }} mtu 1500
  loop: "{{ vlans }}"
  when: item.l3_ip is defined

- name: configure century link vlan
  edgeos_config:
    lines:
      - set interfaces ethernet {{ item.l3_interface }} vif {{ item.vlan_id }} address dhcp
      - set interfaces ethernet {{ item.l3_interface }} vif {{ item.vlan_id }} description {{ item.name }}
      - set interfaces ethernet {{ item.l3_interface }} vif {{ item.vlan_id }} mtu 1500
  loop: "{{ vlans }}"
  when: item.name == 'cl_pppoe'

- name: Include firewall groups vars file
  include_vars:
    file: firewall_groups.yml

- name: configure firewall groups
  edgeos_config:
    lines:
      - set firewall group {{ item.0.type }}-group {{ item.0.name }} {{ item.0.type }} {{ item.1 }}
  with_subelements:
    - "{{ firewall_groups }}"
    - elements

- name: include firewall tasks
  include_tasks: tasks/firewall/fw.yml

- name: include nat tasks
  include_tasks: tasks/firewall/nat.yml

- name: configure eth0.201 (century link pppoe)
  edgeos_config:
    lines:
      - set interfaces ethernet eth0 vif 201 pppoe 0 default-route auto
      - set interfaces ethernet eth0 vif 201 pppoe 0 mtu 1492
      - set interfaces ethernet eth0 vif 201 pppoe 0 name-server auto
      - set interfaces ethernet eth0 vif 201 pppoe 0 password {{ cl_password }}
      - set interfaces ethernet eth0 vif 201 pppoe 0 user-id {{ cl_username }}

- name: set firewall system options
  edgeos_config:
    lines:
      - set firewall options mss-clamp interface-type pppoe
      - set firewall options mss-clamp mss 1452
      - set firewall receive-redirects disable
      - set firewall send-redirects enable
      - set firewall source-validation disable
      - set firewall syn-cookies enable

- name: set OpenVPN static route
  edgeos_config:
    lines:
      - set protocols static route 10.0.60.0/24 next-hop 10.0.3.59

- name: set dhcp-relay servers
  edgeos_config:
    lines:
      - set service dhcp-relay server {{ item }}
  loop: "{{ dhcp_servers }}"

- name: set hardware offloading options
  edgeos_config:
    lines:
      - set system offload ipv4 forwarding enable
      - set system offload ipv4 pppoe disable
      - set system offload ipv4 vlan disable
      - set system offload ipv4 gre disable

- name: set dhcp-relay interfaces
  edgeos_config:
    lines: set service dhcp-relay interface {{ item.l3_interface }}.{{ item.vlan_id }}
  loop: "{{ vlans }}"
  when: item.dhcp|default(false)|bool
