---

- name: configure vlans
  cisco.ios.ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: active
        shutdown: disabled
    state: merged
  loop: "{{ vlans }}"

- name: configure general trunk interfaces
  cisco.ios.ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - "description {{ item.description }}"
      - "switchport mode {{ item.mode }}"
  with_items:
    - {interface: GigabitEthernet1/0/13, mode: trunk, description: esxi-0-pcie1-guests}
    - {interface: GigabitEthernet1/0/14, mode: trunk, description: esxi-0-pcie2-guests}

- name: configure general access interfaces
  cisco.ios.ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - "description {{ item.description }}"
      - "switchport mode {{ item.mode }}"
      - "switchport access vlan {{ item.vlan }}"
  with_items:
    - {interface: GigabitEthernet1/0/1 , mode: access, vlan: 3  , description: ds1515-lan1-mgmt}
    - {interface: GigabitEthernet1/0/2 , mode: access, vlan: 202, description: ds1515-lan2-iSCSI-a}
    - {interface: GigabitEthernet1/0/3 , mode: access, vlan: 203, description: ds1515-lan3-iSCSI-b}
    - {interface: GigabitEthernet1/0/4 , mode: access, vlan: 3  , description: freenas-bce0-mgmt}
    - {interface: GigabitEthernet1/0/5 , mode: access, vlan: 3  , description: freenas-idrac}
    - {interface: GigabitEthernet1/0/6 , mode: access, vlan: 202, description: freenas-igb0-iSCSI-a}
    - {interface: GigabitEthernet1/0/7 , mode: access, vlan: 203, description: freenas-igb1-iSCSI-b}
    - {interface: GigabitEthernet1/0/8 , mode: access, vlan: 3  , description: esxi-0-lan1-mgmt}
    - {interface: GigabitEthernet1/0/9 , mode: access, vlan: 3  , description: taylor-colo-raspi4}
    - {interface: GigabitEthernet1/0/10, mode: access, vlan: 202, description: esxi-0-lan3-iSCSI-a}
    - {interface: GigabitEthernet1/0/11, mode: access, vlan: 203, description: esxi-0-lan4-iSCSI-b}
    - {interface: GigabitEthernet1/0/12, mode: access, vlan: 3  , description: esxi-0-ipmi}
    - {interface: GigabitEthernet1/0/15, mode: access, vlan: 3  , description: box.ad.piccola.us}
    - {interface: GigabitEthernet1/0/16, mode: access, vlan: 3  , description: colo.ad.piccola.us}

- name: configure cs-logan-0 <-> edgerouter-eth0
  cisco.ios.ios_config:
    parents: interface GigabitEthernet1/0/25
    lines:
      - description cs-logan-0<->edgerouter-eth0
      - switchport mode trunk
      - switchport trunk allowed vlan 201

- name: configure cs-logan-0 <-> edgerouter-eth1
  cisco.ios.ios_config:
    parents: interface GigabitEthernet1/0/26
    lines:
      - description cs-logan-0<->edgerouter-eth1
      - switchport mode trunk
      - switchport trunk allowed vlan except 202-205

- name: configure cs-logan-0 <-> ss-logan-0 interface
  cisco.ios.ios_config:
    parents: interface GigabitEthernet1/0/20
    lines:
      - description <-> ss-logan-0
      - switchport mode trunk
      - switchport trunk native vlan 2

# - name: remove config from open ports
#   cisco.ios.ios_config:
#     parents: "interface {{ item.interface }}"
#     lines:
#       - description open
#       - no switchport trunk allowed vlan
#       - no switchport access vlan
#       - no switchport mode access
#       - no switchport trunk native vlan
#   with_items:
#     - {interface: GigabitEthernet1/0/17}
#     - {interface: GigabitEthernet1/0/18}
#     - {interface: GigabitEthernet1/0/19}
#     - {interface: GigabitEthernet1/0/21}
#     - {interface: GigabitEthernet1/0/22}
#     - {interface: GigabitEthernet1/0/23}
#     - {interface: GigabitEthernet1/0/24}
#     - {interface: GigabitEthernet1/0/27}
#     - {interface: GigabitEthernet1/0/28}
#     - {interface: GigabitEthernet1/0/29}
#     - {interface: GigabitEthernet1/0/30}
#     - {interface: GigabitEthernet1/0/31}
#     - {interface: GigabitEthernet1/0/32}
