---

- name: configure vtp
  ios_config:
    lines:
      - vtp mode server
      - "vtp domain {{ vtp_domain }}"
      - "vtp password {{ vtp_password }}"
      - vtp pruning
      - "vtp version {{ vtp_version }}"
  changed_when: false

- name: configure vlans
  ios_vlans:
    config:
      - name: "{{ item.name }}"
        vlan_id: "{{ item.vlan_id }}"
        state: active
        shutdown: disabled
    state: merged
  loop: "{{ vlans }}"

- name: configure general trunk interfaces
  ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - "description {{ item.description }}"
      - "switchport mode {{ item.mode }}"
  with_items:
    - {interface: GigabitEthernet1/0/12, mode: trunk, description: esxi3-pci1-guestNets}
    - {interface: GigabitEthernet1/0/13, mode: trunk, description: esxi3-pci2-guestNets}
    - {interface: GigabitEthernet1/0/20, mode: trunk, description: esxi4-pci1-guestNets}
    - {interface: GigabitEthernet1/0/21, mode: trunk, description: esxi4-pci2-guestNets}

- name: configure general access interfaces
  ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - "description {{ item.description }}"
      - "switchport mode {{ item.mode }}"
      - "switchport access vlan {{ item.vlan }}"
  with_items:
    - {interface: GigabitEthernet1/0/1 , mode: access, vlan: 3  , description: ds1515-lan1-mgmt}
    - {interface: GigabitEthernet1/0/2 , mode: access, vlan: 202, description: ds1515-lan2-iSCSI-a}
    - {interface: GigabitEthernet1/0/3 , mode: access, vlan: 203, description: ds1515-lan3-iSCSI-b}
    - {interface: GigabitEthernet1/0/4 , mode: access, vlan: 3  , description: freenas-bce0-mgmt}
    - {interface: GigabitEthernet1/0/5 , mode: access, vlan: 3  , description: freenas-idrac}
    - {interface: GigabitEthernet1/0/6 , mode: access, vlan: 202, description: freenas-igb0-iSCSI-a}
    - {interface: GigabitEthernet1/0/7 , mode: access, vlan: 203, description: freenas-igb1-iSCSI-b}
    - {interface: GigabitEthernet1/0/8 , mode: access, vlan: 3  , description: esxi3-ob1-mgmt}
    - {interface: GigabitEthernet1/0/9 , mode: access, vlan: 3  , description: esxi3-ilo}
    - {interface: GigabitEthernet1/0/10, mode: access, vlan: 203, description: esxi3-ob3-iscsi-b}
    - {interface: GigabitEthernet1/0/11, mode: access, vlan: 202, description: esxi3-ob4-iscsi-a}
    - {interface: GigabitEthernet1/0/14, mode: access, vlan: 204, description: esxi3-pci3-vMotion}
    - {interface: GigabitEthernet1/0/15, mode: access, vlan: 204, description: esxi3-pci4-vMotion}
    - {interface: GigabitEthernet1/0/16, mode: access, vlan: 3  , description: esxi4-ob1-mgmt}
    - {interface: GigabitEthernet1/0/17, mode: access, vlan: 3  , description: esxi4-ilo}
    - {interface: GigabitEthernet1/0/18, mode: access, vlan: 203, description: esxi4-ob3-iscsi-b}
    - {interface: GigabitEthernet1/0/19, mode: access, vlan: 202, description: esxi4-ob4-iscsi-a}
    - {interface: GigabitEthernet1/0/22, mode: access, vlan: 204, description: esxi4-pci3-vMotion}
    - {interface: GigabitEthernet1/0/23, mode: access, vlan: 204, description: esxi4-pci4-vMotion}
    - {interface: GigabitEthernet1/0/24, mode: access, vlan: 3  , description: dc04}
    - {interface: GigabitEthernet1/0/28, mode: access, vlan: 205, description: esxi3-ob2-iscsi-c}
    - {interface: GigabitEthernet1/0/29, mode: access, vlan: 205, description: esxi4-ob2-iscsi-c}
    - {interface: GigabitEthernet1/0/30, mode: access, vlan: 205, description: freenas-igb2-iSCSI-c}
    - {interface: GigabitEthernet1/0/31, mode: access, vlan: 20 , description: taylor-colo-raspi4}

- name: configure cs-logan-0 <-> edgerouter-eth0
  ios_config:
    parents: interface GigabitEthernet1/0/25
    lines:
      - description cs-logan-0<->edgerouter-eth0
      - switchport mode trunk
      - switchport trunk allowed vlan 201

- name: configure cs-logan-0 <-> edgerouter-eth1
  ios_config:
    parents: interface GigabitEthernet1/0/26
    lines:
      - description cs-logan-0<->edgerouter-eth1
      - switchport mode trunk
      - switchport trunk allowed vlan except 202-205

- name: configure cs-logan-0 <-> ss-logan-0
  ios_config:
    parents: interface GigabitEthernet1/0/27
    lines:
      - description cs-logan-0<->ss-logan-0
      - switchport trunk native vlan 2
      - switchport mode trunk
