---

- name: Include vlans varible file
  include_vars:
    file: vlans.yml

- name: include router \ edgeos tasks
  include_tasks: routers.yml
  when: network_layer == 3

- name: include switch \ ios tasks
  include_tasks: switches.yml
  when: network_layer == 2
