---

- name: configure host naming
  cisco.ios.ios_system:
    hostname: "{{ hostvars[inventory_hostname].hostname }}"
    domain_name: "{{ domain_dns_name }}"

- name: configure vtp
  cisco.ios.ios_config:
    lines:
      - "vtp mode {{ hostvars[inventory_hostname].vtp_mode }}"
      - "vtp domain {{ vtp_domain }}"
      - "vtp password {{ vtp_password }}"
      - vtp pruning
      - "vtp version {{ vtp_version }}"
  changed_when: false

- name: service config
  cisco.ios.ios_config:
    lines:
      - no service pad
      - service timestamps debug uptime
      - service timestamps log uptime
      - service password-encryption

- name: configure jumbo frames
  cisco.ios.ios_config:
    lines:
      - system mtu jumbo 9000
  changed_when: false

- name: configure timezone
  cisco.ios.ios_config:
    lines:
      - clock timezone MST -7 0
  changed_when: false

- name: config ntp
  cisco.ios.ios_ntp:
    server: "{{ item }}"
    state: present
  loop: "{{ ntp_servers }}"
  changed_when: false

- name: configure snmp-server
  cisco.ios.ios_config:
    lines:
      - snmp-server community public RO
      - snmp-server location basement
      - snmp-server contact joey

- name: configure name servers
  cisco.ios.ios_system:
    name_servers:
      - "{{ name_servers[0] }}"
      - "{{ name_servers[1] }}"

- name: Include vlans variable file
  include_vars:
    file: vlans.yml

- name: include switch specific configuration
  include_tasks: "{{ hostvars[inventory_hostname].hostname }}.yml"
  when: hostname is defined

- name: save running to startup when modified
  cisco.ios.ios_config:
    save_when: modified
  changed_when: false
