---

- name: configure vtp
  ios_config:
    lines:
      - vtp mode client
      - "vtp domain {{ vtp_domain }}"
      - "vtp password {{ vtp_password }}"
      - vtp pruning
      - "vtp version {{ vtp_version }}"
  changed_when: false

- name: configure general interfaces
  ios_config:
    parents: "interface {{ item.interface }}"
    lines:
      - "description {{ item.description }}"
      - "switchport mode {{ item.mode }}"
      - "switchport access vlan {{ item.vlan }}"
  with_items:
    - {interface: GigabitEthernet0/1, description: bench-1, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/2, description: bench-2, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/3, description: bench-3, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/4, description: bench-4, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/5, description: bench-5, mode: access, vlan: 3}
    - {interface: GigabitEthernet0/6, description: bench-6, mode: access, vlan: 9}
    - {interface: GigabitEthernet0/7, description: bench-7, mode: access, vlan: 10}

- name: configure ts-logan-0 <-> ss-logan-0 interface
  ios_config:
    parents: interface GigabitEthernet0/8
    lines:
      - description <-> ss-logan-0
      - switchport mode trunk
      - switchport trunk native vlan 2
