---

- name: Create MSP account
  user:
    name: "{{ msp_user_name }}"
    comment: MSP access user account

- name: Add MSP user to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ msp_user_name }}
    line: '{{ msp_user_name }} ALL=(ALL:ALL) ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Set MSP user password
  tags: account
  user:
    name: "{{ msp_user_name }}"
    password: "{{ msp_user_password }}"

- name: Create backup user
  user:
    name: "{{ backup_user_name }}"
    comment: Backup user account for recieving jobs from FreenAS

- name: Add backup user to sudo
  lineinfile:
    path: /etc/sudoers.d/"{{ backup_user_name }}"
    line: '{{ backup_user_name }} ALL=(ALL:ALL) ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Create backup user authorized_key file
  authorized_key:
    user: "{{ backup_user_name }}"
    state: present
    manage_dir: true
    comment: freenas_backups
    key: '{{ item }}'
  with_file:
    - "{{ role_path }}/files/id_rsa.pub"