---

- name: Install parted
  apt:
    pkg: parted
    state: latest

- name: Include openVPN tasks
  include_tasks: openvpn.yml

- name: Include telegraf tasks
  include_tasks: telegraf.yml

- name: Include account tasks
  include_tasks: accounts.yml

- name: Include backup tasks
  include_tasks: backup.yml
