---
python_script_path: /home/pi/Get-BME280Stats.py
telegraf_conf_path: /etc/telegraf/telegraf.conf
telegraf_agent_interval: 10m
telegraf_output_urls: http://dockerlin.piccola.us:8086
telegraf_output_database: temp_metrics
