---

- name: create 99-tailscale.conf
  ansible.builtin.file:
    path: /etc/sysctl.d/99-tailscale.conf
    state: touch
    modification_time: preserve # this makes the task idempotent
    access_time: preserve # this makes the task idempotent
  register: created_tailscale_conf

- name: ipv4.ip_forward
  ansible.builtin.shell:
    cmd: echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.d/99-tailscale.conf
  when: created_tailscale_conf.changed

- name: ipv6.ip_forward
  ansible.builtin.shell:
    cmd: echo 'net.ipv6.conf.all.forwarding = 1' | tee -a /etc/sysctl.d/99-tailscale.conf
  when: created_tailscale_conf.changed

- name: load sysctl.conf
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/99-tailscale.conf
  when: created_tailscale_conf.changed

- name: Configure Tailscale
  include_role:
    name: galaxy_roles/artis3n.tailscale
