---

routers:
  hosts:
    10.0.2.1:
      hostname: cr-logan-0

switches:
  hosts:
    10.0.2.33:
      hostname: cs-logan-0
      vtp_mode: server
    10.0.2.7:
      hostname: ss-logan-0
      vtp_mode: client
    10.0.2.5:
      hostname: ts-logan-1 # garage
      vtp_mode: client
    10.0.2.6:
      hostname: ts-logan-0 # office
      vtp_mode: client

all:
  hosts:
    pi5.piccola.us:
      hostname: pi5
      ansible_user: joey
    raspi-colo.tail42371.ts.net:
      hostname: colo
      ansible_user: joey

pi_home:
  hosts:
    pi5.piccola.us:
      tailscale_args: "--hostname=raspi5-home --advertise-routes=10.0.3.0/24 --accept-routes --advertise-exit-node "

pi_colo:
  hosts:
    raspi-colo.tail42371.ts.net:
      tailscale_args: "--hostname=raspi-colo --accept-routes --advertise-exit-node"


network:
  children:
    routers:
    switches:
