---

routers:
  hosts:
    10.0.2.1:
      hostname: cr-logan-0

switches:
  hosts:
    10.0.2.33:
      hostname: cs-logan-0
      vtp_mode: server
    10.0.2.7:
      hostname: ss-logan-0
      vtp_mode: client
    10.0.2.5:
      hostname: ts-logan-1 # garage
      vtp_mode: client
    10.0.2.6:
      hostname: ts-logan-0 # office
      vtp_mode: client

colo:
  hosts:
    raspi-colo:
      hostname: colo
      # ansible_ssh_port: 5639

raspi-home:
  hosts:
    10.0.3.108:
      hostname: raspi-home

network:
  children:
    routers:
    switches:

debian:
  children:
    puppet:

raspbian:
  children:
    colo:
    raspi-home:
