---

routers:
  hosts:
    10.0.2.1:
      hostname: cr-logan-0

switches:
  hosts:
    10.0.2.33:
      hostname: cs-logan-0
      vtp_mode: server
    10.0.2.7:
      hostname: ss-logan-0
      vtp_mode: client
    10.0.2.5:
      hostname: ts-logan-1
      vtp_mode: client
    # 10.0.2.6:
    #   hostname: ts-logan-0

colo:
  hosts:
    10.0.60.10:
      hostname: colo

network:
  children:
    routers:
    switches:

debian:
  children:
    puppet:

raspbian:
  children:
    colo:
