---
- hosts: puppet
  become: true
  roles:
    - role: base
      tags:
        - base
    - role: puppet
      tags:
        - puppet
    - role: galaxy_roles/gantsign.oh-my-zsh
    - role: galaxy_roles/geerlingguy.ruby
