---

- name: Update apt
  apt: update_cache=yes

- name: Set timezone to American/Denver
  timezone:
    name: "{{ timezone }}"

- name: Install apt packages
  tags: packages
  become: true
  apt:
    force_apt_get: true
    pkg: "{{ apt_packages }}"
    state: present

- name: create /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    content: |
             net.bridge.bridge-nf-call-iptables = 1
             net.ipv4.ip_forward=1
             fs.inotify.max_user_watches=65536
    dest: /etc/sysctl.d/k8s.conf
  register: k8s_conf

- name: sysctl reload in support of sysctl.d/k8s.conf
  ansible.builtin.command: sysctl --system
  when: k8s_conf is changed

- name: Disable swap permanently, persist reboots
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes
  register: disable_swap_permanently

- name: Disable swap for current session
  command: swapoff -a
  become: true
  when: disable_swap_permanently is changed

- name: include controlplane tasks
  include_tasks: controlplane.yml
  when: k8s_component == 'controlplane'

- name: include worker tasks
  include_tasks: worker.yml
  when: k8s_component == 'worker'
