---

- name: Install OpenVPN package
  tags: openvpn
  apt:
    pkg: openvpn
    state: latest

- name: Enable OpenVPN service
  tags: openvpn
  become: true
  systemd:
    name: openvpn@client.service
    enabled: yes
    state: started

- name: Copy over OpenVPN config
  tags: openvpn
  become: true
  template:
    src: "{{ role_path }}/files/joey_colo.conf"
    dest: /etc/openvpn/client.conf
    owner: pi
    mode: 0600
